FROM frengky/web:php7
LABEL maintainer="frengky.lim@gmail.com"

COPY supervisor/crond.ini /etc/supervisor.d/
COPY supervisor/laravel-worker.ini /etc/supervisor.d/
COPY nginx/laravel.conf /etc/nginx/conf.d/default.conf

VOLUME /app
WORKDIR /app
EXPOSE 8080

COPY scripts/docker-entrypoint.laravel.sh /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["supervisord", "-c", "/etc/supervisord.conf"]
